[package]
name = "orml-gradually-update"
version = "0.0.1"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate.git", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-state-machine = { git = "https://github.com/paritytech/substrate.git", optional = true }
sp-io = { package = "sp-io", git = "https://github.com/paritytech/substrate.git", default-features = false }
rstd = { package = "sp-std", git = "https://github.com/paritytech/substrate.git", default-features = false }

[dev-dependencies]
primitives = { package = "sp-core",  git = "https://github.com/paritytech/substrate.git", default-features = false }
orml-utilities = { path = "../utilities", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"rstd/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-state-machine",
]
