[package]
name = "orml-oracle-rpc-runtime-api"
version = "0.4.1-dev"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"
license = "Apache-2.0"
description = "Runtime API module for orml-oracle-rpc."
repository = "https://github.com/open-web3-stack/open-runtime-module-library/tree/master/oracle/rpc/runtime-api"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", version = "3.0.0", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", version = "3.0.0", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
	"sp-std/std"
]
