[package]
name = "orml-weight-meter"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
spin = "0.7.1"
frame-support = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
weight-meter-procedural = { path = "weight-meter-procedural", default-features = false }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "weight-meter-procedural/std",
]
runtime-benchmarks = ["weight-meter-procedural/runtime-benchmarks"]
