name: Master

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        default: true
    - name: Install cargo-unleash
      run: cargo install cargo-unleash --version 1.0.0-alpha.10 #FIXME: change to release once it's ready
    - name: Prepare
      run: make Cargo.toml
    - name: Cargo unleash check
      run: cargo unleash check

