name: Test

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2019-11-08
        components: rustfmt
        target: wasm32-unknown-unknown
        default: true
    - name: Check format
      run: make dev-format-check
    - name: Check with no_std
      run: make dev-check
    - name: Run tests
      run: make dev-test
