name: Test

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2020-05-07
        components: rustfmt
        target: wasm32-unknown-unknown
        override: true
        default: true
    - name: Install Wasm toolchain
      run: rustup target add wasm32-unknown-unknown
    - name: Check format
      run: make dev-format-check
    - name: Install clippy
      run: rustup component add clippy
    - name: Run clippy
      run: cargo clippy
    - name: Update
      run: cargo update
    - name: Check for Wasm
      run: make dev-check
    - name: Run tests
      run: make dev-test
